//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using NSubstitute;
using NUnit.Framework;
using System;

namespace AssemblyCSharpEditor
{
	[TestFixture()]
	public class LogoAnimationTest
	{
		[Test()]
		public void LogoShouldZoomOut ()
		{
			var logo = GetLogoAnimationMock();

			Assert.AreEqual(new Vector3(100,100,100), logo.transform.localScale);
		}

		private LogoAnimation GetLogoAnimationMock()
		{
			return Substitute.For<LogoAnimation>();
		}
	}
}

