//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using NUnit.Framework;
using System;

namespace AssemblyCSharpEditor
{
		[TestFixture()]
		public class PlayerControllerTest
		{
				[Test()]
				public void TestCase ()
				{
				}
		}
}

